// GETTERS
export const YOUR_LOCATION = 'navigator/YOUR_LOCATION'
export const YOUR_CENTER = 'navigator/YOUR_CENTER'
export const YOUR_ZOOM = 'navigator/YOUR_ZOOM'
export const LOADING_COMPLETED = 'navigator/LOADING_COMPLETED'
export const LOCATIONS = 'locationFinder/LOCATIONS'
export const PLACE = 'placeInfo/PLACE'
export const CURRENT_USER = 'auth/CURRENT_USER'
export const TOKEN = 'auth/TOKEN'
export const AUTH_STATUS = 'auth/AUTH_STATUS'
export const CONNECTED = 'auth/CONNECTED'
export const NOTI_STATUS = 'shared/NOTI_STATUS'
export const POST = 'postActions/POST'
export const COMMENTS = 'postActions/COMMENTS'

// MUTATIONS
export const MUTATE_FETCH_LOCATIONS = 'locationFinder/MUTATE_FETCH_LOCATIONS'
export const MUTATE_FIND_YOUR_LOCATION = 'navigator/MUTATE_FIND_YOUR_LOCATION'
export const MUTATE_FETCH_PLACE = 'placeInfo/MUTATE_FETCH_PLACE'
export const MUTATE_CREATE_USER = 'auth/MUTATE_CREATE_USER'
export const MUTATE_LOG_IN = 'auth/MUTATE_LOG_IN'
export const MUTATE_SET_CONNECTION = 'auth/MUTATE_SET_CONNECTION'
export const MUTATE_SET_CURRENT_USER = 'auth/MUTATE_SET_CURRENT_USER'
export const MUTATE_DELETE_CURRENT_USER = 'auth/MUTATE_DELETE_CURRENT_USER'
export const MUTATE_GET_FACEBOOK_USER = 'auth/MUTATE_GET_FACEBOOK_USER'
export const MUTATE_SET_NOTI_STATUS = 'shared/MUTATE_SET_NOTI_STATUS'
export const MUTATE_CHECK_LOGIN = 'auth/MUTATE_CHECK_LOGIN'
export const MUTATE_GET_ALL_POSTS = 'newsFeed/MUTATE_GET_ALL_POSTS'
export const MUTATE_CREATE_POST = 'newsFeed/MUTATE_CREATE_POST'
export const MUTATE_CREATE_COMMENT = 'newsFeed/MUTATE_CREATE_COMMENT'
export const MUTATE_GET_COMMENTS = 'newsFeed/MUTATE_GET_COMMENTS'
export const MUTATE_SHOW_POST = 'newsFeed/MUTATE_SHOW_POST'
export const MUTATE_LIKE = 'postActions/MUTATE_LIKE'

// ACTIONS
export const FIND_YOUR_LOCATION = 'navigator/FIND_YOUR_LOCATION'
export const FETCH_LOCATIONS = 'locationFinder/FETCH_LOCATIONS'
export const FETCH_PLACE = 'placeInfo/FETCH_PLACE'
export const CREATE_USER = 'auth/CREATE_USER'
export const CREATE_POST = 'newsFeed/CREATE_POST'
export const LOG_IN = 'auth/LOG_IN'
export const SET_CONNECTION = 'auth/SET_CONNECTION'
export const SET_CURRENT_USER = 'auth/SET_CURRENT_USER'
export const GET_FACEBOOK_USER = 'auth/GET_FACEBOOK_USER'
export const SET_NOTI_STATUS = 'shared/SET_NOTI_STATUS'
export const CHECK_LOGIN = 'auth/CHECK_LOGIN'
export const LOG_OUT = 'auth/LOG_OUT'
export const GET_ALL_POSTS = 'newsFeed/GET_ALL_POSTS'
export const CREATE_COMMENT = 'newsFeed/CREATE_COMMENT'
export const GET_COMMENTS = 'newsFeed/GET_COMMENTS'
export const SHOW_POST = 'newsFeed/SHOW_POST'
export const LIKE = 'postActions/LIKE'
